### ISSUE TITLE
ModTap shift fires inconsistently

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#122] opened 2019-03-14 00:48 UTC
@kdb424 can fill this with more details since he ran into it, but he wasn't able to use Shift-Click in Minecraft, yet was able to type fine in normal conversations

**Comment by kdb424** [comment] 2019-03-16 00:40
It seems to be "repushing" shift each cycle. The OS needs to get the state that it was pushed, and the state that it was released, but it seems to get that it is pushed on every cycle possibly, throwing off cases where you would hold the key, but works fine when combining the key with another key.. That is my current assumption.

**Comment by kdb424** [comment] 2020-07-13 06:58
I'm going to close this issue as it's actually an "intended feature" and "not a bug"

**Closed by kdb424** 2020-07-13 06:58 UTC
Labels: bug, general firmware
